name: Nethermind API tests CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: curl https://github.com/NethermindEth/sedge/releases/download/v1.3.2/sedge-v1.3.2-linux-arm64 --output sedge
    - run: chmod +x sedge
    - run: ./sedge deps install
    - run: npm install
